from backlib.internal.stdlib.py313.ospath.src.genericpath import (
    commonprefix,
    exists,
    getatime,
    getctime,
    getmtime,
    getsize,
    isdir,
    isfile,
    islink,
    lexists,
    samefile,
    sameopenfile,
    samestat,
)
from backlib.internal.utils.sys import is_nt, is_posix


if is_nt():
    from backlib.internal.stdlib.py313.ospath.src.ntpath import (
        abspath,
        basename,
        commonpath,
        dirname,
        expanduser,
        expandvars,
        isabs,
        isdevdrive,
        isjunction,
        ismount,
        join,
        normcase,
        normpath,
        realpath,
        relpath,
        split,
        splitdrive,
        splitext,
        splitroot,
        supports_unicode_filenames,
    )

elif is_posix():
    from backlib.internal.stdlib.py313.ospath.src.posixpath import (
        abspath,
        basename,
        commonpath,
        dirname,
        expanduser,
        expandvars,
        isabs,
        isdevdrive,
        isjunction,
        ismount,
        join,
        normcase,
        normpath,
        realpath,
        relpath,
        split,
        splitdrive,
        splitext,
        splitroot,
        supports_unicode_filenames,
    )

else:
    detail = "..."
    raise ImportError(detail)


__all__: list[str] = [
    "abspath",
    "basename",
    "commonpath",
    "commonprefix",
    "dirname",
    "exists",
    "expanduser",
    "expandvars",
    "getatime",
    "getctime",
    "getmtime",
    "getsize",
    "isabs",
    "isdevdrive",
    "isdir",
    "isfile",
    "isjunction",
    "islink",
    "ismount",
    "join",
    "lexists",
    "normcase",
    "normpath",
    "realpath",
    "relpath",
    "samefile",
    "sameopenfile",
    "samestat",
    "split",
    "splitdrive",
    "splitext",
    "splitroot",
    "supports_unicode_filenames",
]
