from os.path import (
    abspath,
    basename,
    commonpath,
    commonprefix,
    dirname,
    exists,
    expanduser,
    expandvars,
    getatime,
    getctime,
    getmtime,
    getsize,
    isabs,
    isdir,
    isfile,
    islink,
    ismount,
    join,
    lexists,
    normcase,
    normpath,
    relpath,
    samefile,
    sameopenfile,
    split,
    splitdrive,
    splitext,
    supports_unicode_filenames,
)

from backlib.internal.backports.py310.os_path.internal.os_path import realpath, samestat


__all__: list[str] = [
    "abspath",
    "basename",
    "commonpath",
    "commonprefix",
    "dirname",
    "exists",
    "expanduser",
    "expandvars",
    "getatime",
    "getctime",
    "getmtime",
    "getsize",
    "isabs",
    "isdir",
    "isfile",
    "islink",
    "ismount",
    "join",
    "lexists",
    "normcase",
    "normpath",
    "realpath",
    "relpath",
    "samefile",
    "sameopenfile",
    "samestat",
    "split",
    "splitdrive",
    "splitext",
    "supports_unicode_filenames",
]
